DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  phoneNumber VARCHAR(255) NOT NULL,
  email VARCHAR(50) NOT NULL,
  type CHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL
);
